walkway(slee,baird).
walkway(baird,clemens).
walkway(lockwood,clemens).
walkway(lockwood,studentunion).
walkway(studentunion,bell).
walkway(studentunion,knox).
walkway(bell,furnas).
walkway(furnas,jarvis).
walkway(baldy,lockwood).
walkway(obrian,baldy).
walkway(obrian,park).
walkway(jacobs,park).
walkway(norton,obrian).
walkway(norton,bonner).
walkway(knox,norton).
walkway(norton,capen).
walkway(capen,talbert).
walkway(talbert,natsci).
walkway(natsci,cooke).
walkway(natsci,fronczak).
walkway(fronczak,compcenter).
walkway(hochstetter,cooke).
walkway(dorsheimer,cooke).

